name: Ubuntu 24 VPS

on:
  workflow_dispatch:

jobs:
  vps:
    runs-on: ubuntu-24.04

    steps:
      - name: Install tools
        run: |
          sudo apt update
          sudo apt install -y openssh-server curl

      - name: Start SSH
        run: |
          sudo systemctl enable ssh
          sudo systemctl start ssh

      - name: Start temporary SSH session
        uses: mxschmitt/action-tmate@v3
